language: node_js
node_js:
  - "node"
script:
  - echo "UNIT TESTS - via karma - with code coverage"
  - npm test:unit
after_success:
  - cat ./build/reports/coverage/**/lcov.info | ./node_modules/.bin/coveralls
